"""Optional Promptfoo-format export (spec 03 F5).

Promptfoo's assertion vocabulary does not line up one-to-one with ours, and pretending otherwise would
produce a config that silently checks the wrong thing. So the mapping is explicit and lossy in a
documented way:

    output_matches_regex  -> `regex`             (exact equivalent)
    output_matches_schema -> `is-json` + schema  (exact equivalent)
    must_cite (sources)   -> `icontains-all`     (equivalent for pinned ids; weaker for min_count)
    must_cite (min_count) -> `javascript`        (counts citation-shaped ids in the output)
    must_call_tool        -> `javascript`        (Promptfoo sees final output, not the tool trace,
                                                  so this can only check what the output claims)
    must_escalate         -> `javascript`        (same limitation)

The two `javascript` fallbacks are weaker than the pytest export, which sees the real tool trace. That
is stated in the emitted file so nobody mistakes a green Promptfoo run for a green eval suite.
"""

from __future__ import annotations

import json
from collections.abc import Sequence
from typing import Any

import yaml

from t2e.assertions import DEFAULT_ESCALATION_KEYWORDS, DEFAULT_ESCALATION_TOOLS
from t2e.exporters.cases_jsonl import case_to_record
from t2e.models import Case

FORMAT = "promptfoo"
FILENAME = "promptfooconfig.yaml"

_HEADER = """# Generated by Trace2Evals - do not edit by hand.
#
# version: {version}   cases: {case_count}
# Regenerate with: t2e export --version {version} --format promptfoo
#
# CAVEAT: Promptfoo evaluates the final output text. It does not see the agent's tool trace, so
# `must_call_tool` and `must_escalate` are approximated by inspecting what the output *says*. Those
# two assertions are strictly weaker here than in the generated pytest suite, which checks the real
# trace. Treat this file as a convenience for prompt iteration, not as the authoritative eval gate.
"""

#: Counts citation-shaped evidence ids in the output. Mirrors DEFAULT_CITATION_PATTERN.
_JS_CITATION_COUNT = (
    "(output.match(/\\b[A-Z]{{2,6}}-[A-Z0-9]{{2,}}(?:-[A-Z0-9]+)*\\b/g) || []).length >= {min_count}"
)


def _assertion_for(expectation: dict[str, Any]) -> dict[str, Any] | None:
    kind = expectation.get("kind")

    if kind == "output_matches_regex":
        return {"type": "regex", "value": expectation["pattern"]}

    if kind == "output_matches_schema":
        return {"type": "is-json", "value": expectation["schema"]}

    if kind == "must_cite":
        sources = expectation.get("sources")
        if sources:
            return {"type": "icontains-all", "value": list(sources)}
        min_count = int(expectation.get("min_count", 1))
        return {
            "type": "javascript",
            "value": _JS_CITATION_COUNT.format(min_count=min_count),
        }

    if kind == "must_call_tool":
        tools = [name.strip() for name in str(expectation["tool"]).split(",")]
        checks = " || ".join(f"output.includes({json.dumps(name)})" for name in tools)
        return {
            "type": "javascript",
            # Weaker than the pytest equivalent: it can only see whether the output mentions the tool.
            "value": checks,
        }

    if kind == "must_escalate":
        signals = list(expectation.get("keywords", DEFAULT_ESCALATION_KEYWORDS)) + list(
            expectation.get("tools", DEFAULT_ESCALATION_TOOLS)
        )
        checks = " || ".join(
            f"output.toLowerCase().includes({json.dumps(signal.lower())})" for signal in signals
        )
        return {"type": "javascript", "value": checks}

    return None


def render(cases: Sequence[Case], *, version: str) -> str:
    tests: list[dict[str, Any]] = []
    skipped: list[str] = []

    for case in sorted(cases, key=lambda item: (item.version, item.id)):
        record = case_to_record(case)
        assertions: list[dict[str, Any]] = []
        for expectation in record["expectations"]:
            mapped = _assertion_for(expectation)
            if mapped is None:
                skipped.append(f"{record['case_id']}: {expectation.get('kind')}")
            else:
                assertions.append(mapped)

        test: dict[str, Any] = {
            "description": record["case_id"],
            "vars": {"input": record["input"]},
        }
        if assertions:
            test["assert"] = assertions
        if record["tags"]:
            test["metadata"] = {"tags": record["tags"]}
        tests.append(test)

    config: dict[str, Any] = {
        "description": f"Trace2Evals suite {version}",
        # Left for the user: Promptfoo needs a prompt and a provider, which a trace does not carry.
        "prompts": ["{{input}}"],
        "providers": [],
        "tests": tests,
    }

    body = yaml.safe_dump(config, sort_keys=False, allow_unicode=True, default_flow_style=False)
    header = _HEADER.format(version=version, case_count=len(cases))
    if skipped:
        header += "#\n# Unmapped expectations (no Promptfoo equivalent):\n"
        header += "".join(f"#   - {entry}\n" for entry in skipped)
    return header + "\n" + body
