"""The generated `test_cases.py` pytest stub (spec 03 F5).

It is a *stub* in the honest sense: it contains the cases and the assertions, but it cannot know how to
run your agent. So it imports a `run_agent(case_input)` adapter that you write, and skips with a clear
message until you do. A generated file that pretended to pass without an agent wired in would be worse
than useless in CI.

Assertion helpers are imported from `t2e.assertions` rather than inlined (PLAN.md D-008): one
implementation, tested once, and a stub short enough to read in a sitting.
"""

from __future__ import annotations

from collections.abc import Sequence

from t2e.models import Case

FORMAT = "pytest"
FILENAME = "test_cases.py"

_TEMPLATE = '''"""Generated by Trace2Evals - do not edit by hand.

    version   : {version}
    cases     : {case_count}
    generated : from {source_file}

Regenerate with:

    t2e export --version {version} --format pytest

To run these tests, tell them how to call your agent. Create `conftest.py` next to this file:

    import pytest

    @pytest.fixture
    def run_agent():
        def _run(case_input: str):
            # Call your agent however you like, then return what it did.
            # Any of these works:
            #   * a plain string (the final output)
            #   * a dict: {{"output": ..., "tool_calls": [...], "citations": [...],
            #              "escalated": bool}}
            #   * a t2e.assertions.AgentRun
            from my_agent import investigate
            result = investigate(case_input)
            return {{
                "output": result.text,
                "tool_calls": [call.name for call in result.calls],
                "citations": result.evidence_ids,
                "escalated": result.escalated,
            }}
        return _run

Reporting structured facts (tool_calls, citations, escalated) is always more reliable than making the
assertions infer them from the output text.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from t2e.assertions import assert_all, check_all

CASES_FILE = Path(__file__).with_name("{cases_filename}")


def load_cases() -> list[dict]:
    """Read the exported cases sitting next to this file."""
    if not CASES_FILE.is_file():
        pytest.skip(f"{{CASES_FILE.name}} not found next to this test file")
    records = []
    for line in CASES_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            records.append(json.loads(line))
    return records


CASES = load_cases()

#: Parameter ids so a failure names the case, not an index.
IDS = [case["case_id"] for case in CASES]


def test_cases_file_is_present_and_versioned() -> None:
    """A guard against silently running an empty suite - the failure mode that hides regressions."""
    assert CASES, "no cases loaded: the exported suite is empty"
    assert all(case.get("schema_version") == {schema_version} for case in CASES), (
        "case records were written by a different schema version; re-export with this t2e"
    )


@pytest.mark.parametrize("case", CASES, ids=IDS)
def test_case_has_expectations(case: dict) -> None:
    """A case with no expectations asserts nothing and would pass forever."""
    assert case["expectations"], f"case {{case['case_id']}} has no expectations"


@pytest.mark.parametrize("case", CASES, ids=IDS)
def test_agent_meets_expectations(case: dict, run_agent) -> None:
    """The real eval: run the agent on the case input, then assert every expectation."""
    result = run_agent(case["input"])
    assert_all(result, case["expectations"], case_id=case["case_id"])


def test_report_all_outcomes(run_agent, capsys) -> None:
    """A per-expectation summary, so a red build shows the failure distribution at a glance."""
    rows = []
    for case in CASES:
        outcomes = check_all(run_agent(case["input"]), case["expectations"])
        for outcome in outcomes:
            rows.append((case["case_id"], outcome.kind, "pass" if outcome.passed else "FAIL"))

    with capsys.disabled():
        print()
        print(f"{{'case':<24}} {{'assertion':<24}} result")
        for case_id, kind, status in rows:
            print(f"{{case_id:<24}} {{kind:<24}} {{status}}")

    failed = [row for row in rows if row[2] == "FAIL"]
    assert not failed, f"{{len(failed)}} of {{len(rows)}} expectation(s) failed"
'''


def render(
    cases: Sequence[Case],
    *,
    version: str,
    cases_filename: str = "cases.jsonl",
    source_file: str = "cases.jsonl",
    schema_version: int | None = None,
) -> str:
    from t2e import CASE_SCHEMA_VERSION

    return _TEMPLATE.format(
        version=version,
        case_count=len(cases),
        cases_filename=cases_filename,
        source_file=source_file,
        schema_version=CASE_SCHEMA_VERSION if schema_version is None else schema_version,
    )
